### ISSUE TITLE
It doesnt work 

### ISSUE THREAD

**Issue by fazi1058** [rohammosalli/smart-dns#1]
HI !

I am trying  to run Smart DNS for personal use and I try this  but it didnt work .
as far I know port for dnsmasq is open but dnsmasq doesnt resolve anything 

best regards

**Comment by fazi1058** [comment]
dnsmasq works but in specific network doesnt pass geo-location limitation .
can you help me to troubleshoot?

**Comment by fazi1058** [comment]
Its worked!
Thank you !

**Comment by rohammosalli** [comment]
Hi Faezeh, sorry for the late reply I was busy :) maybe in some providers, you can not run this proxy 

The best way to troubleshoot this kind of problem is to read logs and errors, I highly recommend running smart DNS without docker.
